In [2]:
#importing the necessary libraries
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import pandas as pd
import matplotlib.pyplot as plt
from numpy.linalg import inv

In [3]:
#univariate linear regression closed form
data = pd.read_csv('../datasets/housing/housing_univariate.csv')

In [4]:
# will divide in 8:2 ratio for train and test
#it is ok to call test for now-(consider same as validation)
size = len(data)
train_len = int(size * 0.8)
test_len = size - train_len

In [5]:
# Split the data into training/testing sets

#len(data[:train_len])
#len(data[:test_len])
train = np.array(data[:train_len])
test = np.array(data[:test_len])

In [6]:
# actual training set and also reshaping to (n X 1) arrays
x_train = np.array(train[:,0]).reshape(-1,1)
y_train = np.array(train[:,1]).reshape(-1,1)
x_test = np.array(test[:,0]).reshape(-1,1)
y_test = np.array(test[:,1]).reshape(-1,1)

In [7]:
#might seem redundant but for good readability
X = x_train
Y = y_train
one = np.ones((len(X),1))
#...and add to feature matrix
X = np.concatenate((one, X), 1)
#np.shape(X)

(16512, 2)

In [8]:
X

array([[ 1.    ,  8.3252],
       [ 1.    ,  8.3014],
       [ 1.    ,  7.2574],
       ..., 
       [ 1.    ,  4.1833],
       [ 1.    ,  3.4426],
       [ 1.    ,  3.4009]])

In [9]:
# calculate coefficients using closed-form solution
coeffs = inv(X.transpose().dot(X)).dot(X.transpose()).dot(Y)

In [10]:
np.shape(coeffs)

(2, 1)

In [11]:
coeffs[0]

array([ 47027.44709632])

In [12]:
coeffs[1]

array([ 40795.04535185])

In [13]:
#for test data
X = x_test
Y = y_test
one = np.ones((len(X),1))
#...and add to feature matrix
X = np.concatenate((one, X), 1)

In [14]:
#predicting values
y_pred = X.dot(coeffs)

In [18]:
# root mean square with library
mse = mean_squared_error(y_pred, y_test)
rmse = np.sqrt(mse)
print("Root mean square error : ", rmse)

# root mean square without library
rmse2 = np.sqrt(np.sum(np.square(np.subtract(y_pred,y_test)))/len(y_test))
print("Root mean square error : ", rmse2)

Root mean square error :  72041.9273975
Root mean square error :  72041.9273975


In [19]:
#for multivariate regression
# will be applying the same method as seen above

In [20]:
data2 = pd.read_csv('../datasets/housing/housing_multivariate.csv')

In [21]:
# doing following since data contains null/NAN value
data2 = data2.fillna(method='ffill')

#can also use x = x[~numpy.isnan(x)] for a feature

data2.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms        False
population            False
households            False
median_income         False
median_house_value    False
dtype: bool

In [22]:
size = len(data2)
train_len = int(size * 0.8)
test_len = size - train_len

In [23]:
# Split the data into training/testing sets

#len(data[:train_len])
#len(data[:test_len])
train = np.array(data2[:train_len])
test = np.array(data2[:test_len])

In [24]:
data2.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income  median_house_value  
0         322         126         8.3252              452600  
1        2401        1138         8.3014              358500  
2         496         177         7.2574              352100  
3         558         219         5.6431              341300  
4         565         259         3.8462              342200

In [25]:
# actual training set and also reshaping to (n X 1) arrays
x_train = np.array(train[:,:-1])
y_train = np.array(train[:,-1:])
x_test = np.array(test[:,:-1])
y_test = np.array(test[:,-1:])


In [26]:
np.shape(x_train)


(16512, 8)

In [27]:
X = x_train
Y = y_train
one = np.ones((len(X),1))
#...and add to feature matrix
X = np.concatenate((one, X), 1)
np.shape(X)

(16512, 9)

In [162]:
# calculate coefficients using closed-form solution
coeffs = inv(X.transpose().dot(X)).dot(X.transpose()).dot(Y)

In [163]:
np.shape(coeffs)

(9, 1)

In [164]:
X = x_test
Y = y_test
one = np.ones((len(X),1))
#...and add to feature matrix
X = np.concatenate((one, X),1)
np.shape(X)

(4128, 9)

In [165]:
y_pred = X.dot(coeffs)
coeffs

array([[ -3.48346104e+06],
       [ -4.18941827e+04],
       [ -4.25982141e+04],
       [  1.17622072e+03],
       [ -7.55336093e+00],
       [  8.78825433e+01],
       [ -3.98205325e+01],
       [  7.69986597e+01],
       [  4.01331772e+04]])

In [166]:
mse = mean_squared_error(y_pred, y_test)
rmse = np.sqrt(mse)
print("Root mean square error : ", rmse)

Root mean square error :  61597.6905631


In [167]:
mean_absolute_error(y_pred, y_test)

48187.943621415056